//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	computev1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/compute/v1beta1"
	containerv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/container/v1beta1"
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorConfig) DeepCopyInto(out *AcceleratorConfig) {
	*out = *in
	if in.AcceleratorTypeURI != nil {
		in, out := &in.AcceleratorTypeURI, &out.AcceleratorTypeURI
		*out = new(string)
		**out = **in
	}
	if in.AcceleratorCount != nil {
		in, out := &in.AcceleratorCount, &out.AcceleratorCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorConfig.
func (in *AcceleratorConfig) DeepCopy() *AcceleratorConfig {
	if in == nil {
		return nil
	}
	out := new(AcceleratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingConfig) DeepCopyInto(out *AutoscalingConfig) {
	*out = *in
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(AutoscalingPolicyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingConfig.
func (in *AutoscalingConfig) DeepCopy() *AutoscalingConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyIdentity) DeepCopyInto(out *AutoscalingPolicyIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyIdentity.
func (in *AutoscalingPolicyIdentity) DeepCopy() *AutoscalingPolicyIdentity {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyRef) DeepCopyInto(out *AutoscalingPolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyRef.
func (in *AutoscalingPolicyRef) DeepCopy() *AutoscalingPolicyRef {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuxiliaryNodeGroup) DeepCopyInto(out *AuxiliaryNodeGroup) {
	*out = *in
	if in.NodeGroup != nil {
		in, out := &in.NodeGroup, &out.NodeGroup
		*out = new(NodeGroup)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeGroupID != nil {
		in, out := &in.NodeGroupID, &out.NodeGroupID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuxiliaryNodeGroup.
func (in *AuxiliaryNodeGroup) DeepCopy() *AuxiliaryNodeGroup {
	if in == nil {
		return nil
	}
	out := new(AuxiliaryNodeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuxiliaryServicesConfig) DeepCopyInto(out *AuxiliaryServicesConfig) {
	*out = *in
	if in.MetastoreConfig != nil {
		in, out := &in.MetastoreConfig, &out.MetastoreConfig
		*out = new(MetastoreConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SparkHistoryServerConfig != nil {
		in, out := &in.SparkHistoryServerConfig, &out.SparkHistoryServerConfig
		*out = new(SparkHistoryServerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuxiliaryServicesConfig.
func (in *AuxiliaryServicesConfig) DeepCopy() *AuxiliaryServicesConfig {
	if in == nil {
		return nil
	}
	out := new(AuxiliaryServicesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfig) DeepCopyInto(out *ClusterConfig) {
	*out = *in
	if in.ConfigBucket != nil {
		in, out := &in.ConfigBucket, &out.ConfigBucket
		*out = new(refsv1beta1.StorageBucketRef)
		**out = **in
	}
	if in.TempBucket != nil {
		in, out := &in.TempBucket, &out.TempBucket
		*out = new(refsv1beta1.StorageBucketRef)
		**out = **in
	}
	if in.GCEClusterConfig != nil {
		in, out := &in.GCEClusterConfig, &out.GCEClusterConfig
		*out = new(GCEClusterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MasterConfig != nil {
		in, out := &in.MasterConfig, &out.MasterConfig
		*out = new(InstanceGroupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerConfig != nil {
		in, out := &in.WorkerConfig, &out.WorkerConfig
		*out = new(InstanceGroupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SecondaryWorkerConfig != nil {
		in, out := &in.SecondaryWorkerConfig, &out.SecondaryWorkerConfig
		*out = new(InstanceGroupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SoftwareConfig != nil {
		in, out := &in.SoftwareConfig, &out.SoftwareConfig
		*out = new(SoftwareConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InitializationActions != nil {
		in, out := &in.InitializationActions, &out.InitializationActions
		*out = make([]NodeInitializationAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EncryptionConfig != nil {
		in, out := &in.EncryptionConfig, &out.EncryptionConfig
		*out = new(EncryptionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoscalingConfig != nil {
		in, out := &in.AutoscalingConfig, &out.AutoscalingConfig
		*out = new(AutoscalingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityConfig != nil {
		in, out := &in.SecurityConfig, &out.SecurityConfig
		*out = new(SecurityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LifecycleConfig != nil {
		in, out := &in.LifecycleConfig, &out.LifecycleConfig
		*out = new(LifecycleConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EndpointConfig != nil {
		in, out := &in.EndpointConfig, &out.EndpointConfig
		*out = new(EndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MetastoreConfig != nil {
		in, out := &in.MetastoreConfig, &out.MetastoreConfig
		*out = new(MetastoreConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DataprocMetricConfig != nil {
		in, out := &in.DataprocMetricConfig, &out.DataprocMetricConfig
		*out = new(DataprocMetricConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfig.
func (in *ClusterConfig) DeepCopy() *ClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIdentity) DeepCopyInto(out *ClusterIdentity) {
	*out = *in
	if in.parent != nil {
		in, out := &in.parent, &out.parent
		*out = new(ClusterParent)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIdentity.
func (in *ClusterIdentity) DeepCopy() *ClusterIdentity {
	if in == nil {
		return nil
	}
	out := new(ClusterIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMetrics) DeepCopyInto(out *ClusterMetrics) {
	*out = *in
	if in.HdfsMetrics != nil {
		in, out := &in.HdfsMetrics, &out.HdfsMetrics
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.YarnMetrics != nil {
		in, out := &in.YarnMetrics, &out.YarnMetrics
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMetrics.
func (in *ClusterMetrics) DeepCopy() *ClusterMetrics {
	if in == nil {
		return nil
	}
	out := new(ClusterMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterParent) DeepCopyInto(out *ClusterParent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterParent.
func (in *ClusterParent) DeepCopy() *ClusterParent {
	if in == nil {
		return nil
	}
	out := new(ClusterParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRef) DeepCopyInto(out *ClusterRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRef.
func (in *ClusterRef) DeepCopy() *ClusterRef {
	if in == nil {
		return nil
	}
	out := new(ClusterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatusObservedState) DeepCopyInto(out *ClusterStatusObservedState) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Detail != nil {
		in, out := &in.Detail, &out.Detail
		*out = new(string)
		**out = **in
	}
	if in.StateStartTime != nil {
		in, out := &in.StateStartTime, &out.StateStartTime
		*out = new(string)
		**out = **in
	}
	if in.Substate != nil {
		in, out := &in.Substate, &out.Substate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatusObservedState.
func (in *ClusterStatusObservedState) DeepCopy() *ClusterStatusObservedState {
	if in == nil {
		return nil
	}
	out := new(ClusterStatusObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialInstanceConfig) DeepCopyInto(out *ConfidentialInstanceConfig) {
	*out = *in
	if in.EnableConfidentialCompute != nil {
		in, out := &in.EnableConfidentialCompute, &out.EnableConfidentialCompute
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialInstanceConfig.
func (in *ConfidentialInstanceConfig) DeepCopy() *ConfidentialInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(ConfidentialInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataprocCluster) DeepCopyInto(out *DataprocCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataprocCluster.
func (in *DataprocCluster) DeepCopy() *DataprocCluster {
	if in == nil {
		return nil
	}
	out := new(DataprocCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataprocCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataprocClusterList) DeepCopyInto(out *DataprocClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataprocCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataprocClusterList.
func (in *DataprocClusterList) DeepCopy() *DataprocClusterList {
	if in == nil {
		return nil
	}
	out := new(DataprocClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataprocClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataprocClusterObservedState) DeepCopyInto(out *DataprocClusterObservedState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataprocClusterObservedState.
func (in *DataprocClusterObservedState) DeepCopy() *DataprocClusterObservedState {
	if in == nil {
		return nil
	}
	out := new(DataprocClusterObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataprocClusterSpec) DeepCopyInto(out *DataprocClusterSpec) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(refsv1beta1.ProjectRef)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ClusterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VirtualClusterConfig != nil {
		in, out := &in.VirtualClusterConfig, &out.VirtualClusterConfig
		*out = new(VirtualClusterConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataprocClusterSpec.
func (in *DataprocClusterSpec) DeepCopy() *DataprocClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DataprocClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataprocClusterStatus) DeepCopyInto(out *DataprocClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(DataprocClusterObservedState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataprocClusterStatus.
func (in *DataprocClusterStatus) DeepCopy() *DataprocClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DataprocClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataprocMetricConfig) DeepCopyInto(out *DataprocMetricConfig) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]DataprocMetricConfig_Metric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataprocMetricConfig.
func (in *DataprocMetricConfig) DeepCopy() *DataprocMetricConfig {
	if in == nil {
		return nil
	}
	out := new(DataprocMetricConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataprocMetricConfig_Metric) DeepCopyInto(out *DataprocMetricConfig_Metric) {
	*out = *in
	if in.MetricSource != nil {
		in, out := &in.MetricSource, &out.MetricSource
		*out = new(string)
		**out = **in
	}
	if in.MetricOverrides != nil {
		in, out := &in.MetricOverrides, &out.MetricOverrides
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataprocMetricConfig_Metric.
func (in *DataprocMetricConfig_Metric) DeepCopy() *DataprocMetricConfig_Metric {
	if in == nil {
		return nil
	}
	out := new(DataprocMetricConfig_Metric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataprocServiceRef) DeepCopyInto(out *DataprocServiceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataprocServiceRef.
func (in *DataprocServiceRef) DeepCopy() *DataprocServiceRef {
	if in == nil {
		return nil
	}
	out := new(DataprocServiceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskConfig) DeepCopyInto(out *DiskConfig) {
	*out = *in
	if in.BootDiskType != nil {
		in, out := &in.BootDiskType, &out.BootDiskType
		*out = new(string)
		**out = **in
	}
	if in.BootDiskSizeGB != nil {
		in, out := &in.BootDiskSizeGB, &out.BootDiskSizeGB
		*out = new(int32)
		**out = **in
	}
	if in.NumLocalSsds != nil {
		in, out := &in.NumLocalSsds, &out.NumLocalSsds
		*out = new(int32)
		**out = **in
	}
	if in.LocalSsdInterface != nil {
		in, out := &in.LocalSsdInterface, &out.LocalSsdInterface
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskConfig.
func (in *DiskConfig) DeepCopy() *DiskConfig {
	if in == nil {
		return nil
	}
	out := new(DiskConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionConfig) DeepCopyInto(out *EncryptionConfig) {
	*out = *in
	if in.GCEPDKMSKeyRef != nil {
		in, out := &in.GCEPDKMSKeyRef, &out.GCEPDKMSKeyRef
		*out = new(refsv1beta1.KMSCryptoKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionConfig.
func (in *EncryptionConfig) DeepCopy() *EncryptionConfig {
	if in == nil {
		return nil
	}
	out := new(EncryptionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointConfig) DeepCopyInto(out *EndpointConfig) {
	*out = *in
	if in.EnableHTTPPortAccess != nil {
		in, out := &in.EnableHTTPPortAccess, &out.EnableHTTPPortAccess
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointConfig.
func (in *EndpointConfig) DeepCopy() *EndpointConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCEClusterConfig) DeepCopyInto(out *GCEClusterConfig) {
	*out = *in
	if in.ZoneURI != nil {
		in, out := &in.ZoneURI, &out.ZoneURI
		*out = new(string)
		**out = **in
	}
	if in.NetworkRef != nil {
		in, out := &in.NetworkRef, &out.NetworkRef
		*out = new(refsv1beta1.ComputeNetworkRef)
		**out = **in
	}
	if in.SubnetworkRef != nil {
		in, out := &in.SubnetworkRef, &out.SubnetworkRef
		*out = new(refsv1beta1.ComputeSubnetworkRef)
		**out = **in
	}
	if in.InternalIPOnly != nil {
		in, out := &in.InternalIPOnly, &out.InternalIPOnly
		*out = new(bool)
		**out = **in
	}
	if in.PrivateIPV6GoogleAccess != nil {
		in, out := &in.PrivateIPV6GoogleAccess, &out.PrivateIPV6GoogleAccess
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccountRef != nil {
		in, out := &in.ServiceAccountRef, &out.ServiceAccountRef
		*out = new(refsv1beta1.IAMServiceAccountRef)
		**out = **in
	}
	if in.ServiceAccountScopes != nil {
		in, out := &in.ServiceAccountScopes, &out.ServiceAccountScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReservationAffinity != nil {
		in, out := &in.ReservationAffinity, &out.ReservationAffinity
		*out = new(ReservationAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeGroupAffinity != nil {
		in, out := &in.NodeGroupAffinity, &out.NodeGroupAffinity
		*out = new(NodeGroupAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.ShieldedInstanceConfig != nil {
		in, out := &in.ShieldedInstanceConfig, &out.ShieldedInstanceConfig
		*out = new(ShieldedInstanceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfidentialInstanceConfig != nil {
		in, out := &in.ConfidentialInstanceConfig, &out.ConfidentialInstanceConfig
		*out = new(ConfidentialInstanceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCEClusterConfig.
func (in *GCEClusterConfig) DeepCopy() *GCEClusterConfig {
	if in == nil {
		return nil
	}
	out := new(GCEClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GkeClusterConfig) DeepCopyInto(out *GkeClusterConfig) {
	*out = *in
	if in.GkeClusterTarget != nil {
		in, out := &in.GkeClusterTarget, &out.GkeClusterTarget
		*out = new(containerv1beta1.ClusterRef)
		**out = **in
	}
	if in.NodePoolTarget != nil {
		in, out := &in.NodePoolTarget, &out.NodePoolTarget
		*out = make([]GkeNodePoolTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GkeClusterConfig.
func (in *GkeClusterConfig) DeepCopy() *GkeClusterConfig {
	if in == nil {
		return nil
	}
	out := new(GkeClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GkeNodePoolConfig) DeepCopyInto(out *GkeNodePoolConfig) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(GkeNodePoolConfig_GkeNodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(GkeNodePoolConfig_GkeNodePoolAutoscalingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GkeNodePoolConfig.
func (in *GkeNodePoolConfig) DeepCopy() *GkeNodePoolConfig {
	if in == nil {
		return nil
	}
	out := new(GkeNodePoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GkeNodePoolConfig_GkeNodeConfig) DeepCopyInto(out *GkeNodePoolConfig_GkeNodeConfig) {
	*out = *in
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.LocalSsdCount != nil {
		in, out := &in.LocalSsdCount, &out.LocalSsdCount
		*out = new(int32)
		**out = **in
	}
	if in.Preemptible != nil {
		in, out := &in.Preemptible, &out.Preemptible
		*out = new(bool)
		**out = **in
	}
	if in.Accelerators != nil {
		in, out := &in.Accelerators, &out.Accelerators
		*out = make([]GkeNodePoolConfig_GkeNodePoolAcceleratorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinCPUPlatform != nil {
		in, out := &in.MinCPUPlatform, &out.MinCPUPlatform
		*out = new(string)
		**out = **in
	}
	if in.BootDiskKMSKey != nil {
		in, out := &in.BootDiskKMSKey, &out.BootDiskKMSKey
		*out = new(string)
		**out = **in
	}
	if in.Spot != nil {
		in, out := &in.Spot, &out.Spot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GkeNodePoolConfig_GkeNodeConfig.
func (in *GkeNodePoolConfig_GkeNodeConfig) DeepCopy() *GkeNodePoolConfig_GkeNodeConfig {
	if in == nil {
		return nil
	}
	out := new(GkeNodePoolConfig_GkeNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GkeNodePoolConfig_GkeNodePoolAcceleratorConfig) DeepCopyInto(out *GkeNodePoolConfig_GkeNodePoolAcceleratorConfig) {
	*out = *in
	if in.AcceleratorCount != nil {
		in, out := &in.AcceleratorCount, &out.AcceleratorCount
		*out = new(int64)
		**out = **in
	}
	if in.AcceleratorType != nil {
		in, out := &in.AcceleratorType, &out.AcceleratorType
		*out = new(string)
		**out = **in
	}
	if in.GpuPartitionSize != nil {
		in, out := &in.GpuPartitionSize, &out.GpuPartitionSize
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GkeNodePoolConfig_GkeNodePoolAcceleratorConfig.
func (in *GkeNodePoolConfig_GkeNodePoolAcceleratorConfig) DeepCopy() *GkeNodePoolConfig_GkeNodePoolAcceleratorConfig {
	if in == nil {
		return nil
	}
	out := new(GkeNodePoolConfig_GkeNodePoolAcceleratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GkeNodePoolConfig_GkeNodePoolAutoscalingConfig) DeepCopyInto(out *GkeNodePoolConfig_GkeNodePoolAutoscalingConfig) {
	*out = *in
	if in.MinNodeCount != nil {
		in, out := &in.MinNodeCount, &out.MinNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.MaxNodeCount != nil {
		in, out := &in.MaxNodeCount, &out.MaxNodeCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GkeNodePoolConfig_GkeNodePoolAutoscalingConfig.
func (in *GkeNodePoolConfig_GkeNodePoolAutoscalingConfig) DeepCopy() *GkeNodePoolConfig_GkeNodePoolAutoscalingConfig {
	if in == nil {
		return nil
	}
	out := new(GkeNodePoolConfig_GkeNodePoolAutoscalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GkeNodePoolTarget) DeepCopyInto(out *GkeNodePoolTarget) {
	*out = *in
	if in.NodePool != nil {
		in, out := &in.NodePool, &out.NodePool
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodePoolConfig != nil {
		in, out := &in.NodePoolConfig, &out.NodePoolConfig
		*out = new(GkeNodePoolConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GkeNodePoolTarget.
func (in *GkeNodePoolTarget) DeepCopy() *GkeNodePoolTarget {
	if in == nil {
		return nil
	}
	out := new(GkeNodePoolTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityConfig) DeepCopyInto(out *IdentityConfig) {
	*out = *in
	if in.UserServiceAccountMapping != nil {
		in, out := &in.UserServiceAccountMapping, &out.UserServiceAccountMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityConfig.
func (in *IdentityConfig) DeepCopy() *IdentityConfig {
	if in == nil {
		return nil
	}
	out := new(IdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceFlexibilityPolicy) DeepCopyInto(out *InstanceFlexibilityPolicy) {
	*out = *in
	if in.ProvisioningModelMix != nil {
		in, out := &in.ProvisioningModelMix, &out.ProvisioningModelMix
		*out = new(InstanceFlexibilityPolicy_ProvisioningModelMix)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceSelectionList != nil {
		in, out := &in.InstanceSelectionList, &out.InstanceSelectionList
		*out = make([]InstanceFlexibilityPolicy_InstanceSelection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceFlexibilityPolicy.
func (in *InstanceFlexibilityPolicy) DeepCopy() *InstanceFlexibilityPolicy {
	if in == nil {
		return nil
	}
	out := new(InstanceFlexibilityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceFlexibilityPolicyObservedState) DeepCopyInto(out *InstanceFlexibilityPolicyObservedState) {
	*out = *in
	if in.InstanceSelectionResults != nil {
		in, out := &in.InstanceSelectionResults, &out.InstanceSelectionResults
		*out = make([]InstanceFlexibilityPolicy_InstanceSelectionResult, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceFlexibilityPolicyObservedState.
func (in *InstanceFlexibilityPolicyObservedState) DeepCopy() *InstanceFlexibilityPolicyObservedState {
	if in == nil {
		return nil
	}
	out := new(InstanceFlexibilityPolicyObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceFlexibilityPolicy_InstanceSelection) DeepCopyInto(out *InstanceFlexibilityPolicy_InstanceSelection) {
	*out = *in
	if in.MachineTypes != nil {
		in, out := &in.MachineTypes, &out.MachineTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rank != nil {
		in, out := &in.Rank, &out.Rank
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceFlexibilityPolicy_InstanceSelection.
func (in *InstanceFlexibilityPolicy_InstanceSelection) DeepCopy() *InstanceFlexibilityPolicy_InstanceSelection {
	if in == nil {
		return nil
	}
	out := new(InstanceFlexibilityPolicy_InstanceSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceFlexibilityPolicy_InstanceSelectionResult) DeepCopyInto(out *InstanceFlexibilityPolicy_InstanceSelectionResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceFlexibilityPolicy_InstanceSelectionResult.
func (in *InstanceFlexibilityPolicy_InstanceSelectionResult) DeepCopy() *InstanceFlexibilityPolicy_InstanceSelectionResult {
	if in == nil {
		return nil
	}
	out := new(InstanceFlexibilityPolicy_InstanceSelectionResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceFlexibilityPolicy_InstanceSelectionResultObservedState) DeepCopyInto(out *InstanceFlexibilityPolicy_InstanceSelectionResultObservedState) {
	*out = *in
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.VmCount != nil {
		in, out := &in.VmCount, &out.VmCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceFlexibilityPolicy_InstanceSelectionResultObservedState.
func (in *InstanceFlexibilityPolicy_InstanceSelectionResultObservedState) DeepCopy() *InstanceFlexibilityPolicy_InstanceSelectionResultObservedState {
	if in == nil {
		return nil
	}
	out := new(InstanceFlexibilityPolicy_InstanceSelectionResultObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceFlexibilityPolicy_ProvisioningModelMix) DeepCopyInto(out *InstanceFlexibilityPolicy_ProvisioningModelMix) {
	*out = *in
	if in.StandardCapacityBase != nil {
		in, out := &in.StandardCapacityBase, &out.StandardCapacityBase
		*out = new(int32)
		**out = **in
	}
	if in.StandardCapacityPercentAboveBase != nil {
		in, out := &in.StandardCapacityPercentAboveBase, &out.StandardCapacityPercentAboveBase
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceFlexibilityPolicy_ProvisioningModelMix.
func (in *InstanceFlexibilityPolicy_ProvisioningModelMix) DeepCopy() *InstanceFlexibilityPolicy_ProvisioningModelMix {
	if in == nil {
		return nil
	}
	out := new(InstanceFlexibilityPolicy_ProvisioningModelMix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceGroupConfig) DeepCopyInto(out *InstanceGroupConfig) {
	*out = *in
	if in.NumInstances != nil {
		in, out := &in.NumInstances, &out.NumInstances
		*out = new(int32)
		**out = **in
	}
	if in.ImageURI != nil {
		in, out := &in.ImageURI, &out.ImageURI
		*out = new(computev1beta1.ImageRef)
		**out = **in
	}
	if in.MachineTypeURI != nil {
		in, out := &in.MachineTypeURI, &out.MachineTypeURI
		*out = new(string)
		**out = **in
	}
	if in.DiskConfig != nil {
		in, out := &in.DiskConfig, &out.DiskConfig
		*out = new(DiskConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Preemptibility != nil {
		in, out := &in.Preemptibility, &out.Preemptibility
		*out = new(string)
		**out = **in
	}
	if in.Accelerators != nil {
		in, out := &in.Accelerators, &out.Accelerators
		*out = make([]AcceleratorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinCPUPlatform != nil {
		in, out := &in.MinCPUPlatform, &out.MinCPUPlatform
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceGroupConfig.
func (in *InstanceGroupConfig) DeepCopy() *InstanceGroupConfig {
	if in == nil {
		return nil
	}
	out := new(InstanceGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceReference) DeepCopyInto(out *InstanceReference) {
	*out = *in
	if in.InstanceName != nil {
		in, out := &in.InstanceName, &out.InstanceName
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = new(string)
		**out = **in
	}
	if in.PublicEciesKey != nil {
		in, out := &in.PublicEciesKey, &out.PublicEciesKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceReference.
func (in *InstanceReference) DeepCopy() *InstanceReference {
	if in == nil {
		return nil
	}
	out := new(InstanceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KerberosConfig) DeepCopyInto(out *KerberosConfig) {
	*out = *in
	if in.EnableKerberos != nil {
		in, out := &in.EnableKerberos, &out.EnableKerberos
		*out = new(bool)
		**out = **in
	}
	if in.RootPrincipalPasswordURI != nil {
		in, out := &in.RootPrincipalPasswordURI, &out.RootPrincipalPasswordURI
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyURI != nil {
		in, out := &in.KMSKeyURI, &out.KMSKeyURI
		*out = new(refsv1beta1.KMSCryptoKeyRef)
		**out = **in
	}
	if in.KeystoreURI != nil {
		in, out := &in.KeystoreURI, &out.KeystoreURI
		*out = new(string)
		**out = **in
	}
	if in.TruststoreURI != nil {
		in, out := &in.TruststoreURI, &out.TruststoreURI
		*out = new(string)
		**out = **in
	}
	if in.KeystorePasswordURI != nil {
		in, out := &in.KeystorePasswordURI, &out.KeystorePasswordURI
		*out = new(string)
		**out = **in
	}
	if in.KeyPasswordURI != nil {
		in, out := &in.KeyPasswordURI, &out.KeyPasswordURI
		*out = new(string)
		**out = **in
	}
	if in.TruststorePasswordURI != nil {
		in, out := &in.TruststorePasswordURI, &out.TruststorePasswordURI
		*out = new(string)
		**out = **in
	}
	if in.CrossRealmTrustRealm != nil {
		in, out := &in.CrossRealmTrustRealm, &out.CrossRealmTrustRealm
		*out = new(string)
		**out = **in
	}
	if in.CrossRealmTrustKdc != nil {
		in, out := &in.CrossRealmTrustKdc, &out.CrossRealmTrustKdc
		*out = new(string)
		**out = **in
	}
	if in.CrossRealmTrustAdminServer != nil {
		in, out := &in.CrossRealmTrustAdminServer, &out.CrossRealmTrustAdminServer
		*out = new(string)
		**out = **in
	}
	if in.CrossRealmTrustSharedPasswordURI != nil {
		in, out := &in.CrossRealmTrustSharedPasswordURI, &out.CrossRealmTrustSharedPasswordURI
		*out = new(string)
		**out = **in
	}
	if in.KdcDbKeyURI != nil {
		in, out := &in.KdcDbKeyURI, &out.KdcDbKeyURI
		*out = new(string)
		**out = **in
	}
	if in.TgtLifetimeHours != nil {
		in, out := &in.TgtLifetimeHours, &out.TgtLifetimeHours
		*out = new(int32)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KerberosConfig.
func (in *KerberosConfig) DeepCopy() *KerberosConfig {
	if in == nil {
		return nil
	}
	out := new(KerberosConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesClusterConfig) DeepCopyInto(out *KubernetesClusterConfig) {
	*out = *in
	if in.KubernetesNamespace != nil {
		in, out := &in.KubernetesNamespace, &out.KubernetesNamespace
		*out = new(string)
		**out = **in
	}
	if in.GkeClusterConfig != nil {
		in, out := &in.GkeClusterConfig, &out.GkeClusterConfig
		*out = new(GkeClusterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KubernetesSoftwareConfig != nil {
		in, out := &in.KubernetesSoftwareConfig, &out.KubernetesSoftwareConfig
		*out = new(KubernetesSoftwareConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesClusterConfig.
func (in *KubernetesClusterConfig) DeepCopy() *KubernetesClusterConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesSoftwareConfig) DeepCopyInto(out *KubernetesSoftwareConfig) {
	*out = *in
	if in.ComponentVersion != nil {
		in, out := &in.ComponentVersion, &out.ComponentVersion
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesSoftwareConfig.
func (in *KubernetesSoftwareConfig) DeepCopy() *KubernetesSoftwareConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesSoftwareConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleConfig) DeepCopyInto(out *LifecycleConfig) {
	*out = *in
	if in.IdleDeleteTtl != nil {
		in, out := &in.IdleDeleteTtl, &out.IdleDeleteTtl
		*out = new(string)
		**out = **in
	}
	if in.AutoDeleteTime != nil {
		in, out := &in.AutoDeleteTime, &out.AutoDeleteTime
		*out = new(string)
		**out = **in
	}
	if in.AutoDeleteTtl != nil {
		in, out := &in.AutoDeleteTtl, &out.AutoDeleteTtl
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleConfig.
func (in *LifecycleConfig) DeepCopy() *LifecycleConfig {
	if in == nil {
		return nil
	}
	out := new(LifecycleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleConfigObservedState) DeepCopyInto(out *LifecycleConfigObservedState) {
	*out = *in
	if in.IdleStartTime != nil {
		in, out := &in.IdleStartTime, &out.IdleStartTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleConfigObservedState.
func (in *LifecycleConfigObservedState) DeepCopy() *LifecycleConfigObservedState {
	if in == nil {
		return nil
	}
	out := new(LifecycleConfigObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedGroupConfig) DeepCopyInto(out *ManagedGroupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedGroupConfig.
func (in *ManagedGroupConfig) DeepCopy() *ManagedGroupConfig {
	if in == nil {
		return nil
	}
	out := new(ManagedGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedGroupConfigObservedState) DeepCopyInto(out *ManagedGroupConfigObservedState) {
	*out = *in
	if in.InstanceTemplateName != nil {
		in, out := &in.InstanceTemplateName, &out.InstanceTemplateName
		*out = new(string)
		**out = **in
	}
	if in.InstanceGroupManagerName != nil {
		in, out := &in.InstanceGroupManagerName, &out.InstanceGroupManagerName
		*out = new(string)
		**out = **in
	}
	if in.InstanceGroupManagerURI != nil {
		in, out := &in.InstanceGroupManagerURI, &out.InstanceGroupManagerURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedGroupConfigObservedState.
func (in *ManagedGroupConfigObservedState) DeepCopy() *ManagedGroupConfigObservedState {
	if in == nil {
		return nil
	}
	out := new(ManagedGroupConfigObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetastoreConfig) DeepCopyInto(out *MetastoreConfig) {
	*out = *in
	if in.DataprocMetastoreService != nil {
		in, out := &in.DataprocMetastoreService, &out.DataprocMetastoreService
		*out = new(DataprocServiceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetastoreConfig.
func (in *MetastoreConfig) DeepCopy() *MetastoreConfig {
	if in == nil {
		return nil
	}
	out := new(MetastoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroup) DeepCopyInto(out *NodeGroup) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeGroupConfig != nil {
		in, out := &in.NodeGroupConfig, &out.NodeGroupConfig
		*out = new(InstanceGroupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroup.
func (in *NodeGroup) DeepCopy() *NodeGroup {
	if in == nil {
		return nil
	}
	out := new(NodeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupAffinity) DeepCopyInto(out *NodeGroupAffinity) {
	*out = *in
	if in.NodeGroupRef != nil {
		in, out := &in.NodeGroupRef, &out.NodeGroupRef
		*out = new(computev1beta1.NodeGroupRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupAffinity.
func (in *NodeGroupAffinity) DeepCopy() *NodeGroupAffinity {
	if in == nil {
		return nil
	}
	out := new(NodeGroupAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInitializationAction) DeepCopyInto(out *NodeInitializationAction) {
	*out = *in
	if in.ExecutableFile != nil {
		in, out := &in.ExecutableFile, &out.ExecutableFile
		*out = new(string)
		**out = **in
	}
	if in.ExecutionTimeout != nil {
		in, out := &in.ExecutionTimeout, &out.ExecutionTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInitializationAction.
func (in *NodeInitializationAction) DeepCopy() *NodeInitializationAction {
	if in == nil {
		return nil
	}
	out := new(NodeInitializationAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationAffinity) DeepCopyInto(out *ReservationAffinity) {
	*out = *in
	if in.ConsumeReservationType != nil {
		in, out := &in.ConsumeReservationType, &out.ConsumeReservationType
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationAffinity.
func (in *ReservationAffinity) DeepCopy() *ReservationAffinity {
	if in == nil {
		return nil
	}
	out := new(ReservationAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	if in.KerberosConfig != nil {
		in, out := &in.KerberosConfig, &out.KerberosConfig
		*out = new(KerberosConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityConfig != nil {
		in, out := &in.IdentityConfig, &out.IdentityConfig
		*out = new(IdentityConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceIdentity) DeepCopyInto(out *ServiceIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceIdentity.
func (in *ServiceIdentity) DeepCopy() *ServiceIdentity {
	if in == nil {
		return nil
	}
	out := new(ServiceIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShieldedInstanceConfig) DeepCopyInto(out *ShieldedInstanceConfig) {
	*out = *in
	if in.EnableSecureBoot != nil {
		in, out := &in.EnableSecureBoot, &out.EnableSecureBoot
		*out = new(bool)
		**out = **in
	}
	if in.EnableVTPM != nil {
		in, out := &in.EnableVTPM, &out.EnableVTPM
		*out = new(bool)
		**out = **in
	}
	if in.EnableIntegrityMonitoring != nil {
		in, out := &in.EnableIntegrityMonitoring, &out.EnableIntegrityMonitoring
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShieldedInstanceConfig.
func (in *ShieldedInstanceConfig) DeepCopy() *ShieldedInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(ShieldedInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoftwareConfig) DeepCopyInto(out *SoftwareConfig) {
	*out = *in
	if in.ImageVersion != nil {
		in, out := &in.ImageVersion, &out.ImageVersion
		*out = new(string)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OptionalComponents != nil {
		in, out := &in.OptionalComponents, &out.OptionalComponents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoftwareConfig.
func (in *SoftwareConfig) DeepCopy() *SoftwareConfig {
	if in == nil {
		return nil
	}
	out := new(SoftwareConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkHistoryServerConfig) DeepCopyInto(out *SparkHistoryServerConfig) {
	*out = *in
	if in.DataprocCluster != nil {
		in, out := &in.DataprocCluster, &out.DataprocCluster
		*out = new(refsv1beta1.DataprocClusterRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkHistoryServerConfig.
func (in *SparkHistoryServerConfig) DeepCopy() *SparkHistoryServerConfig {
	if in == nil {
		return nil
	}
	out := new(SparkHistoryServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupConfig) DeepCopyInto(out *StartupConfig) {
	*out = *in
	if in.RequiredRegistrationFraction != nil {
		in, out := &in.RequiredRegistrationFraction, &out.RequiredRegistrationFraction
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupConfig.
func (in *StartupConfig) DeepCopy() *StartupConfig {
	if in == nil {
		return nil
	}
	out := new(StartupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterConfig) DeepCopyInto(out *VirtualClusterConfig) {
	*out = *in
	if in.StagingBucket != nil {
		in, out := &in.StagingBucket, &out.StagingBucket
		*out = new(string)
		**out = **in
	}
	if in.KubernetesClusterConfig != nil {
		in, out := &in.KubernetesClusterConfig, &out.KubernetesClusterConfig
		*out = new(KubernetesClusterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AuxiliaryServicesConfig != nil {
		in, out := &in.AuxiliaryServicesConfig, &out.AuxiliaryServicesConfig
		*out = new(AuxiliaryServicesConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterConfig.
func (in *VirtualClusterConfig) DeepCopy() *VirtualClusterConfig {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterConfig)
	in.DeepCopyInto(out)
	return out
}
