#!/usr/bin/env bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}

if [[ -n "${PREBUILT_TAG:-}" ]]; then
  IMAGE_PREFIX=gcr.io/gke-release-staging/cnrm/
  export CONTROLLER_IMG=${IMAGE_PREFIX}controller:${PREBUILT_TAG}
  export RECORDER_IMG=${IMAGE_PREFIX}recorder:${PREBUILT_TAG}
  export WEBHOOK_IMG=${IMAGE_PREFIX}webhook:${PREBUILT_TAG}
  export DELETION_DEFENDER_IMG=${IMAGE_PREFIX}deletiondefender:${PREBUILT_TAG}
  export UNMANAGED_DETECTOR_IMG=${IMAGE_PREFIX}unmanageddetector:${PREBUILT_TAG}

  export OPERATOR_IMG=${IMAGE_PREFIX}operator:${PREBUILT_TAG}
else
  . dev/tasks/build-images
fi

cd ${REPO_ROOT}

kustomize build operator/config/default | sed -e "s@image:.*@image: ${OPERATOR_IMG}@g" | kubectl apply -f -
kubectl set env statefulset/configconnector-operator -n configconnector-operator-system IMAGE_PREFIX=gcr.io/gke-release-staging/cnrm/
kubectl wait statefulset -n configconnector-operator-system configconnector-operator  --for=jsonpath=.status.readyReplicas=1


kubectl apply -f - <<EOF
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  mode: namespaced
EOF

kubectl apply -f - <<EOF
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: default
spec:
  #version: 1.2.3
  googleServiceAccount: "kcc@fake-project.iam.gserviceaccount.com"
EOF