apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
  name: billingbudgets.billingbudgets.cnrm.cloud.google.com
spec:
  group: billingbudgets.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: BillingBudget
    listKind: BillingBudgetList
    plural: billingbudgets
    shortNames:
    - gcpbillingbudget
    - gcpbillingbudgets
    singular: billingbudget
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BillingBudget is the Schema for the BillingBudget API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BillingBudgetSpec defines the desired state of BillingBudget
            properties:
              amount:
                description: Required. Budgeted amount.
                properties:
                  lastPeriodAmount:
                    description: Use the last period's actual spend as the budget
                      for the present period. LastPeriodAmount can only be set when
                      the budget's time period is a [Filter.calendar_period][google.cloud.billing.budgets.v1.Filter.calendar_period].
                      It cannot be set in combination with [Filter.custom_period][google.cloud.billing.budgets.v1.Filter.custom_period].
                    type: object
                  specifiedAmount:
                    description: A specified amount to use as the budget. `currency_code`
                      is optional. If specified when creating a budget, it must match
                      the currency of the billing account. If specified when updating
                      a budget, it must match the currency_code of the existing budget.
                      The `currency_code` is provided on output.
                    type: string
                type: object
              budgetFilter:
                description: Optional. Filters that define which resources are used
                  to compute the actual spend against the budget.
                properties:
                  calendarPeriod:
                    description: Optional. Specifies to track usage for recurring
                      calendar period. For example, assume that CalendarPeriod.QUARTER
                      is set. The budget tracks usage from April 1 to June 30, when
                      the current calendar month is April, May, June. After that,
                      it tracks usage from July 1 to September 30 when the current
                      calendar month is July, August, September, so on.
                    type: string
                  creditTypes:
                    description: |-
                      Optional. If
                       [Filter.credit_types_treatment][google.cloud.billing.budgets.v1.Filter.credit_types_treatment]
                       is INCLUDE_SPECIFIED_CREDITS, this is a list of credit types to be
                       subtracted from gross cost to determine the spend for threshold
                       calculations. See [a list of acceptable credit type
                       values](https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables#credits-type).

                       If
                       [Filter.credit_types_treatment][google.cloud.billing.budgets.v1.Filter.credit_types_treatment]
                       is **not** INCLUDE_SPECIFIED_CREDITS, this field must be empty.
                    items:
                      type: string
                    type: array
                  creditTypesTreatment:
                    description: Optional. If not set, default behavior is `INCLUDE_ALL_CREDITS`.
                    type: string
                  customPeriod:
                    description: Optional. Specifies to track usage from any start
                      date (required) to any end date (optional). This time period
                      is static, it does not recur.
                    properties:
                      endDate:
                        description: Optional. The end date of the time period. Budgets
                          with elapsed end date won't be processed. If unset, specifies
                          to track all usage incurred since the start_date.
                        type: string
                      startDate:
                        description: Required. The start date must be after January
                          1, 2017.
                        type: string
                    type: object
                  projects:
                    description: Optional. A set of projects of the form `projects/{project}`,
                      specifying that usage from only this set of projects should
                      be included in the budget. If omitted, the report includes all
                      usage for the billing account, regardless of which project the
                      usage occurred on.
                    items:
                      type: string
                    type: array
                  resourceAncestors:
                    description: Optional. A set of folder and organization names
                      of the form `folders/{folderId}` or `organizations/{organizationId}`,
                      specifying that usage from only this set of folders and organizations
                      should be included in the budget. If omitted, the budget includes
                      all usage that the billing account pays for. If the folder or
                      organization contains projects that are paid for by a different
                      Cloud Billing account, the budget *doesn't* apply to those projects.
                    items:
                      type: string
                    type: array
                  services:
                    description: 'Optional. A set of services of the form `services/{service_id}`,
                      specifying that usage from only this set of services should
                      be included in the budget. If omitted, the report includes usage
                      for all the services. The service names are available through
                      the Catalog API: https://cloud.google.com/billing/v1/how-tos/catalog-api.'
                    items:
                      type: string
                    type: array
                  subaccounts:
                    description: Optional. A set of subaccounts of the form `billingAccounts/{account_id}`,
                      specifying that usage from only this set of subaccounts should
                      be included in the budget. If a subaccount is set to the name
                      of the parent account, usage from the parent account is included.
                      If the field is omitted, the report includes usage from the
                      parent account and all subaccounts, if they exist.
                    items:
                      type: string
                    type: array
                type: object
              displayName:
                description: User data for display name in UI. The name must be less
                  than or equal to 60 characters.
                type: string
              notificationsRule:
                description: Optional. Rules to apply to notifications sent based
                  on budget spend and thresholds.
                properties:
                  disableDefaultIAMRecipients:
                    description: Optional. When set to true, disables default notifications
                      sent when a threshold is exceeded. Default notifications are
                      sent to those with Billing Account Administrator and Billing
                      Account User IAM roles for the target account.
                    type: boolean
                  enableProjectLevelRecipients:
                    description: |-
                      Optional. When set to true, and when the budget has a single project
                       configured, notifications will be sent to project level recipients of that
                       project. This field will be ignored if the budget has multiple or no
                       project configured.

                       Currently, project level recipients are the users with `Owner` role on a
                       cloud project.
                    type: boolean
                  monitoringNotificationChannels:
                    description: |-
                      Optional. Email targets to send notifications to when a threshold is
                       exceeded. This is in addition to the `DefaultIamRecipients` who receive
                       alert emails based on their billing account IAM role. The value is the full
                       REST resource name of a Cloud Monitoring email notification channel with
                       the form `projects/{project_id}/notificationChannels/{channel_id}`. A
                       maximum of 5 email notifications are allowed.

                       To customize budget alert email recipients with monitoring notification
                       channels, you _must create the monitoring notification channels before
                       you link them to a budget_. For guidance on setting up notification
                       channels to use with budgets, see
                       [Customize budget alert email
                       recipients](https://cloud.google.com/billing/docs/how-to/budgets-notification-recipients).

                       For Cloud Billing budget alerts, you _must use email notification
                       channels_. The other types of notification channels are _not_
                       supported, such as Slack, SMS, or PagerDuty. If you want to
                       [send budget notifications to
                       Slack](https://cloud.google.com/billing/docs/how-to/notify#send_notifications_to_slack),
                       use a pubsubTopic and configure
                       [programmatic
                       notifications](https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications).
                    items:
                      type: string
                    type: array
                  pubsubTopic:
                    description: |-
                      Optional. The name of the Pub/Sub topic where budget-related messages are
                       published, in the form `projects/{project_id}/topics/{topic_id}`. Updates
                       are sent to the topic at regular intervals; the timing of the updates is
                       not dependent on the [threshold rules](#thresholdrule) you've set.

                       Note that if you want your
                       [Pub/Sub JSON
                       object](https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications#notification_format)
                       to contain data for `alertThresholdExceeded`, you need at least one
                       [alert threshold rule](#thresholdrule). When you set threshold rules, you
                       must also enable at least one of the email notification options, either
                       using the default IAM recipients or Cloud Monitoring email notification
                       channels.

                       To use Pub/Sub topics with budgets, you must do the following:

                       1. Create the Pub/Sub topic
                       before connecting it to your budget. For guidance, see
                       [Manage programmatic budget alert
                       notifications](https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications).

                       2. Grant the API caller the `pubsub.topics.setIamPolicy` permission on
                       the Pub/Sub topic. If not set, the API call fails with PERMISSION_DENIED.
                       For additional details on Pub/Sub roles and permissions, see
                       [Permissions required for this
                       task](https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications#permissions_required_for_this_task).
                    type: string
                  schemaVersion:
                    description: Optional. Required when [NotificationsRule.pubsub_topic][google.cloud.billing.budgets.v1.NotificationsRule.pubsub_topic]
                      is set. The schema version of the notification sent to [NotificationsRule.pubsub_topic][google.cloud.billing.budgets.v1.NotificationsRule.pubsub_topic].
                      Only "1.0" is accepted. It represents the JSON schema as defined
                      in https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications#notification_format.
                    type: string
                type: object
              resourceID:
                description: The BillingBudget name. If not given, the metadata.name
                  will be used.
                type: string
              thresholdRules:
                description: |-
                  Optional. Rules that trigger alerts (notifications of thresholds being
                   crossed) when spend exceeds the specified percentages of the budget.

                   Optional for `pubsubTopic` notifications.

                   Required if using email notifications.
                items:
                  properties:
                    spendBasis:
                      description: Optional. The type of basis used to determine if
                        spend has passed the threshold. Behavior defaults to CURRENT_SPEND
                        if not set.
                      type: string
                    thresholdPercent:
                      description: 'Required. Send an alert when this threshold is
                        exceeded. This is a 1.0-based percentage, so 0.5 = 50%. Validation:
                        non-negative number.'
                      type: number
                  type: object
                type: array
            type: object
          status:
            description: BillingBudgetStatus defines the config connector machine
              state of BillingBudget
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique specifier for the BillingBudget resource in
                  GCP.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              observedState:
                description: ObservedState is the state of the resource as most recently
                  observed in GCP.
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
